#!/usr/bin/perl

use strict;
use DBI;
use Expect;
use FindBin;
use Digest::SHA1 qw(sha1_hex);

my $h=DBI->connect("DBI:mysql::mysql_read_default_file=$FindBin::Bin/.my.cnf");

my $s=$h->prepare(<<SQL);
Select device.*, snippet.command
From device, snippet
Where Not disable And itime is Not Null
And device.model=snippet.model And snippet.name=?
SQL
$s->execute($ARGV[0]);

while(my $r=$s->fetchrow_hashref)
{
 print $r->{name}, "\t[", $r->{host}, "]\n"	if -t;

 my $z=new Expect;
 $z->slave->stty(qw(-echo));
 $z->raw_pty(1);
 $z->log_stdout(0);
 $z->restart_timeout_upon_receive(1);
 $z->spawn(qw(/usr/bin/plink -batch -i), "$FindBin::Bin/.ssh/Backup.ppk", "Backup\@$r->{host}");
 $z->send($r->{command}."\n");
 $z->expect(10);
 undef $z;
}

__END__
